[fix] fix args in compute_reinforce_rej_outcome_advantage
```
  File "/nfs/ofs-llab-volume/users/fengyu/new_verl/verl/verl/trainer/main_ppo.py", line 194, in run
    trainer.fit()
  File "/nfs/ofs-llab-volume/users/fengyu/new_verl/verl/verl/trainer/ppo/ray_trainer.py", line 954, in fit
    batch = compute_advantage(batch,
  File "/nfs/ofs-llab-volume/users/fengyu/new_verl/verl/verl/trainer/ppo/ray_trainer.py", line 238, in compute_advantage
    advantages, returns = core_algos.compute_reinforce_rej_outcome_advantage(
TypeError: compute_reinforce_rej_outcome_advantage() missing 1 required positional argument: 'index'
```
fix bug miss param in compute_reinforce_rej_outcome_advantage